### ISSUE TITLE
EstimatorKerasEmbedding.predict_embedding() return value inconsistent

### ISSUE THREAD

**Issue by Abdul-Moeed** [theislab/sfaira#1]
`EstimatorKerasEmbedding.predict_embedding()` returns `np.ndarray` when `model_type` is `ae`, but returns `[np.ndarray]` when `model_type `is `vaevamp`.

**Comment by le-ander** [comment]
currently, vae and vaevamp models return a list of `[z, z_mean, z_log_var]` for predict_embedding() while the ae returns `z` only.

@davidsebfischer what's your opinion on this? is this an inconsistency we need to resolve (eg. return `[embedding, None, None]` for the ae model?

**Comment by le-ander** [comment]
makes sense, I'll take care of that.

**Comment by le-ander** [comment]
@mk017 @Abdul-Moeed please note that we now only return the mean embedding for estimator.predict_embedding() (so simply a numpy array. 

we return z, zmean, z_var now with estimator.predict_embedding_variational()
