### ISSUE TITLE
schema for Dataset.id

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#111]
I'm pretty sure I have read a thread between @Zethson and @davidsebfischer on this, but cannot find it.
A couple of questions:

1. Have we settled on a schema for Dataset.id?
2. As this most likely involves using Dataset.organ, how do we deal with organ names (coming from ontology) that contain spaces? just replace space by underscore?
3. Once we have a harmonised schema, can we just create the id automatically based on the attributes set in the constructor (like self.year, self.organ, self.organism et.?)

**Comment by Zethson** [comment]
Maybe you were thinking of this thread?

https://github.com/theislab/sfaira/issues/57

**Comment by le-ander** [comment]
nah, something else I think

**Comment by Zethson** [comment]
This is how I am currently generating the ID:
https://github.com/theislab/sfaira/pull/89/files#diff-4321091ee1ec2fd54ffe5c2eb77ac003bcebc543c805fccc3988a0d4896db3c4R129

We should absolutely standardize this 110%!

**Comment by Zethson** [comment]
> nah, something else I think

We were discussing this on the sfaira_team_cookie mattermost channel. Maybe you need to scroll up a little bit.

**Comment by davidsebfischer** [comment]
Adding to what we talked about last time, `Dataset`has an attribute `_directory_formatted_id` which has all the slashes etc removed, can be keep `id`maximally humanly readable, ie keep the full DOI, and use the transformation as in `_directory_formatted_id` if we use this as file names (eg. for cache files). The loader `.py`file can be the same ID entirely without the DOI, in this case we do not have any formatting issues anyway. 

Secondly, `organ` and `protocol` are used when defining the ID, these are not necessarily single words anymore now that we use ontologies for that, so we have to take care when transforming these. Maybe just take ontology name and strip it from special characters?

**Comment by le-ander** [comment]
I started implementing this. two sections of the ID that are a little tricky @davidsebfischer :

1. we use the first author of the paper in the ID, however firstauthor is not a metadata field in our sfaira datasets (and hence makes autogeneration of the ID difficult. I suggest we either use the lastauthor of the paper in the ID or make the firstauthor also a metadata field
2. the way we currently implement the numbering of the datasets in the ID of the DatasetGroupManyFiles (001 to 00x) assumes that there is no other dataloader from that paper. do you think this is a valid assumption

**Comment by davidsebfischer** [comment]
>     1. we use the first author of the paper in the ID, however firstauthor is not a metadata field in our sfaira datasets (and hence makes autogeneration of the ID difficult. I suggest we either use the lastauthor of the paper in the ID or make the firstauthor also a metadata field

`.author` is usually first author right now for the ones that I recently saw, if not we should change it to that. Moving forward, `.author` could also be a list of all authors. We could just use the first one if that s the case. In any case I'd use `.author`.

>     2. the way we currently implement the numbering of the datasets in the ID of the DatasetGroupManyFiles (001 to 00x) assumes that there is no other dataloader from that paper. do you think this is a valid assumption

It's fine if the numbering only holds for one sub group, mostly necessary to make otherwise identifcal IDs unique.

**Comment by Zethson** [comment]
That's kind of how I implemented it.
Random code snippets of it:

```
    author = sfaira_questionary(function='text',
                                    question='Author(s):',
                                    default='Einstein, Albert; Hawking, Stephen')
        self.template_attributes.author = author.split(';') if ';' in author else author

        first_author = author[0] if isinstance(author, list) else author
        try:
            first_author_lastname = first_author.split(',')[0]
        except KeyError:
            print('[bold yellow] First author was not in the expected format. Using full first author for the id.')
            first_author_lastname = first_author
```

**Comment by lazappi** [comment]
Not relevant to implementation but I would suggest you will get more unique dataset names by using first author rather than last author which are probably easier to remember.

**Comment by davidsebfischer** [comment]
> Not relevant to implementation but I would suggest you will get more unique dataset names by using first author rather than last author which are probably easier to remember.

exactly my thoughts!

**Comment by le-ander** [comment]
yes, agreed. how about this: self.author should be either the first author or a list of authors. if it's a list we just use the first member of that list.

I think for now self.author is still mainly last authors (I think this field used to be called self.lab), but I'll change that

**Comment by davidsebfischer** [comment]
I am adopting some of these rules in #102 already.

**Comment by davidsebfischer** [comment]
Are there defaults if `.organ`is not set and `.obs_key_organ` is set instead? We could just set it to "x" in these cases.

**Comment by Zethson** [comment]
Default is 'NA'.
