### ISSUE TITLE
HESC UBERON ontology

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#115]
I'm kind of stuck aligning some of the human datasets to ontology. for example the HCL human embryonic stem cell dataset. cannot find something matching in uberon for HESC. any suggestion @davidsebfischer ?

**Comment by davidsebfischer** [comment]
hESC is cell culture so I would group these using formalisms we want to use for these systems: 

- [ ] Specifically, i would label these based on the `derived from`formalism, which is https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000358&viewMode=All&siblings=false for hESC I believe? 

Can we:

- [ ] add a "cell_system" meta data item constrained in an ontology that we define for now, which is ("tissue", "cell culture": ("homogenous cell culture", "heterogenous cell culture")) -> organoid would be "heterogenous cell culture"
- [ ] use `.organ`for the derived from ontology and 
- [ ] add a meta data item which is `differentiated_to`or so to extend this characterisation for in vitro differentiation setups? This would not be necessary in this case as it s not differentiated to anything

**Comment by le-ander** [comment]
@davidsebfischer I saw you just labeled the HESC as `blastocyst` for now. Is that a temp. fix or would we keep this annotation?

**Comment by davidsebfischer** [comment]
It is the source organ so yes right?

**Comment by le-ander** [comment]
adressed in #173
