### ISSUE TITLE
automatic cache creates 2 directories

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#127]
Both caches contain a cached file, one under `cache_dir/cache/flattened_doi/file` and one under `cache_dir/flattened_doi/cache/file`. We are separating the the `cache_dir` from the raw data storage already, so we don't need to put a `cache` subdirectory under that. In principle, `cache_dir/flattened_doi/file` would be possible but just in case that raw and cache directory coincide, `cache_dir/flattened_doi/cache/file` is a good alternative. This way, the user also has the option to group all raw and cached files belonging to one data set under one directory with this setting.

**Comment by davidsebfischer** [comment]
Addressed in https://github.com/theislab/sfaira/commit/4c2ae220f8bc83a042c071564b2eb8e356282d56

**Comment by le-ander** [comment]
One thought on this @davidsebfischer 
do we really need an explicit cache path? Isn't the point of a cache to some extent that it's something transparent that the user doesn't really have to think about?

How about we just remove the cache path argument alltogether and just automatically create a folder named "cache" in the user's local sfaira data repo?

**Comment by davidsebfischer** [comment]
Caches will change more frequently (because of meta data or cell type anntotation updates for example), so this gives the user the ability to use differently backed-up partitions. Moreover, the entire cache can be easily deleted if it s together in one directory, this would not be an issue as it can always be recreated easily and does not require downloads.

**Comment by le-ander** [comment]
Hm, I see your points.
How about setting the cache_path to data_repo_path+"cache" if cache_path is not specified by the user?
From a user perspective I think I'd expect sfaira caching to happen (if I don't disable it) even without specifying a separate cache location on disk.

**Comment by davidsebfischer** [comment]
Yes good idea, the default now `cache_dir/flattened_doi/cache/file` then becomes `data_dir/flattened_doi/cache/file` which is good because studies are grouped together!

**Comment by le-ander** [comment]
same for meta_path
