### ISSUE TITLE
Dataset properties consistency

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#136]
@davidsebfischer I just randomly came across some inconsistencies in the code of the Dataset class attributes:

https://github.com/theislab/sfaira/blob/61547eb782a89eeb94dc848e652263cffce03d2c/sfaira/data/base.py#L948

shouldnt this say: 
```python
            if self.meta is None and self._ADATA_IDS_SFAIRA.author not in self.meta.columns:
```

and this one:

https://github.com/theislab/sfaira/blob/61547eb782a89eeb94dc848e652263cffce03d2c/sfaira/data/base.py#L992

shouldn't this say:
```python
            if self.meta is None and self._ADATA_IDS_SFAIRA.doi not in self.meta.columns:
```

Just want to double check in case I'm misunderstanding some of this code

**Comment by davidsebfischer** [comment]
Being able to evaluate `self._ADATA_IDS_SFAIRA.healthy not in self.meta.columns`  implies that `self.meta is not None`, so this should be or I think, ie first check if there is meta data to start with and if there is, check if the attribute is in there. `or` groups all cases in which this attribute is not in meta.

**Comment by le-ander** [comment]
makes sense, just asking because it's `and` for all the other properties, such as here:

https://github.com/theislab/sfaira/blob/61547eb782a89eeb94dc848e652263cffce03d2c/sfaira/data/base.py#L974

**Comment by davidsebfischer** [comment]
We should probably change these?
