### ISSUE TITLE
cannot import sfaira

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#138]
currently, import ing the sfaira package is broken (both on dev and anotation_csv):

```pytb
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-67a34ea818d4> in <module>
      7 import zipfile
      8 import scipy.io
----> 9 import sfaira #from sfaira.data.interactive import DatasetInteractive
     10 import scarches as sca
     11 

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/__init__.py in <module>
      6 # import sfaira.models
      7 import sfaira.genomes
----> 8 import sfaira.data
      9 import sfaira.consts as consts
     10 import sfaira.versions

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/__init__.py in <module>
----> 1 from .base import DatasetBase, DatasetBaseGroupLoadingOneFile, DatasetBaseGroupLoadingManyFiles, \
      2     DatasetGroup, DatasetGroupDirectoryOriented, \
      3     DatasetSuperGroup
      4 from . import dataloaders
      5 from .dataloaders import DatasetSuperGroupSfaira

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py in <module>
   2104 
   2105 
-> 2106 class DatasetSuperGroup:
   2107     """
   2108     Container for multiple DatasetGroup instances.

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py in DatasetSuperGroup()
   2113     adata: Union[None, anndata.AnnData]
   2114     fn_backed: Union[None, PathLike]
-> 2115     dataset_groups: Union[List[DatasetGroup], List[DatasetSuperGroup]]
   2116 
   2117     def __init__(self, dataset_groups: Union[None, List[DatasetGroup], List[DatasetSuperGroup]]):

NameError: name 'DatasetSuperGroup' is not defined
```

Can DatasetSuperGroup really take other DatasetSuperGroup as dataset_groups input?

**Comment by davidsebfischer** [comment]
> Can DatasetSuperGroup really take other DatasetSuperGroup as dataset_groups input?

Yes this is important for nested cases.
I think we can solve it like this: https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class

**Comment by davidsebfischer** [comment]
So dev already has `from __future__ import annotations` for this purpose in data base, is this on dev?

**Comment by davidsebfischer** [comment]
At least for the constructor `dataset_groups: Union[None, List[DatasetGroup], List[DatasetSuperGroup]]` it should be fine, maybe the issue arises only when attributes are typed as above, if so we could just delete this typing. Do you know anything about that @Zethson?

**Comment by le-ander** [comment]
ha, ok. so I am on python 3.6, so `from __future__ import annotations` throws an error, hence I commented that out and hit this error. should we support python <3.7 at all?
python 3.7 was released mid 2017

**Comment by Zethson** [comment]
> At least for the constructor `dataset_groups: Union[None, List[DatasetGroup], List[DatasetSuperGroup]]` it should be fine, maybe the issue arises only when attributes are typed as above, if so we could just delete this typing. Do you know anything about that @Zethson?

Types are never checked by the interpreter at runtime. They're only used by IDEs or tools like MyPy

**Comment by Zethson** [comment]
> ha, ok. so I am on python 3.6, so `from __future__ import annotations` throws an error, hence I commented that out and hit this error. should we support python <3.7 at all?
> python 3.7 was released mid 2017

Ignore 3.6 imo. 3.7+ is fine.
Hell, 3.10 is around the corner :)

**Comment by davidsebfischer** [comment]
`python>=3.7` would be fine for me!

**Comment by Zethson** [comment]
Funfact: Our CI currently tests against 3.7 and 3.8 only anyways. They are by far the most used versions.

**Comment by le-ander** [comment]
okay, I guess I'll have to somehow upgrade my gpu container...strange that tensorflow publishes their official tf containers with such an old python version
