### ISSUE TITLE
Cell ontology names containing commas

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#140]
I have encountered some CL names that contain a comma (eg. https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000625&viewMode=PreferredRoots&siblings=false)

@davidsebfischer should we switch our celltype csvs to tab separated in order to accomodate for such labels?

**Comment by davidsebfischer** [comment]
yes, good idea! Can you just run a script over all csvs that replaces the first comma in each line with a tab? This also occured in the ones that I looked at.

**Comment by le-ander** [comment]
yep, will do. will also change filenames from csv to tsv

I'll also change the functions that write these files

**Comment by le-ander** [comment]
closed in 36e9440e90d2270a764cf24ee2c28107ac5f98e2
