### ISSUE TITLE
Improved tutorials

### ISSUE THREAD

**Issue by Zethson** [theislab/sfaira#143]
Huhu,

I will try to improve the tutorials to improve the accessibility of sfaira. 
1. I suggest that we move https://github.com/theislab/sfaira_tutorials to a tutorial/notebooks folder in this repository. Less confusing navigation for newcomers even if we host the notebooks somewhere + easier contributions from external people.
2. I may not be the correct person to most of the code for the tutorials since I am still newish to sfaira :) I will however take care of everything else.
3. @davidsebfischer suggest to cover
3.1 User interface for model deployment from zenodo
3.2 Different ways of accessing data from the data repo
3.3 Extracting gene-wise information across datagroups

Any other wishes and suggestions?

Related issue: https://github.com/theislab/sfaira/issues/64 (Can be closed I guess?)

**Comment by davidsebfischer** [comment]
1.: Scanpy did this before but inflates the repository a lot becacuse the notebooks are large and PRs becomes messy because of it, I like keeping it separate for these reasons, what do you think?

**Comment by Zethson** [comment]
> 1.: Scanpy did this before but inflates the repository a lot becacuse the notebooks are large and PRs becomes messy because of it, I like keeping it separate for these reasons, what do you think?

Ahh, I see. Yeah then we can keep them separate :+1:

**Comment by le-ander** [comment]
>     2. I may not be the correct person to most of the code for the tutorials since I am still newish to sfaira :) I will however take care of everything else.

Hi Lukas,
no worries, happy to help if something is unclear. The existing tutorials should be more or less functional and already cover quite some bit of the points we want to cover. Do you think you can use these as a starting point so we can get our polished tutorials ready for revision? Whenever there is something unclear or you need input on the code / API side, I'm more than happy to pitch in!

**Comment by Zethson** [comment]
Yup. I'll try to get at this in the next couple of days.

**Comment by davidsebfischer** [comment]
@Zethson do you have code locally that you want to contribute or should we close this for now?

**Comment by Zethson** [comment]
> @Zethson do you have code locally that you want to contribute or should we close this for now?

Don't have any. Let's close this.
