### ISSUE TITLE
reading obo files on windows breaks

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#161]
on windows, obonet cannot read local obo files (breaks with an decoding error). this is also the reason why our current CI builds on windows break. when directly providing the download URL instead of the filepath to read_obo(), it works even on windows.

@davidsebfischer is there any benefit of downloading the obo files to disk first or can we remove the whole download part and just feed the link to the obo file directly into obonet?

**Comment by davidsebfischer** [comment]
They are not super small so it definitely has the advantage of speeding things up, secondly, sfaira would only work with a working internet connection if this caching did not work, so I would definitely keep it. We can catch the reading error though and download again if this occurs (ie always for windows)?
