### ISSUE TITLE
YAML format in CLI 

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#163]
An example YAML is here https://github.com/theislab/sfaira/blob/dev/sfaira/data/dataloaders/loaders/d10_1038_s41586_020_2922_4/human_lung_2020_x_travaglini_001.yaml. Most of these can be filled as before. Download urls can be separated by data set but do not have to be (e.g. if it is not possible).

Note that 
- bio_sample_obs_key
- individual_obs_key
- tech_sample_obs_key
are new and can either be a column name, or a set of column names separated by "*", these are then assembled into unique identifiers internally.

**Comment by Zethson** [comment]
> bio_sample_obs_key
> individual_obs_key
> tech_sample_obs_key

But we shouldn't prompt for them since they are no mandatory, right?

**Comment by davidsebfischer** [comment]
No, they are not mandatory, are you only asking for mandatory fields though? I think the CLI could just go through all fields and one could just skip steps. Where is the list of mandatory fields?

**Comment by Zethson** [comment]
Can also do that. Fine with me.
