### ISSUE TITLE
class-free load in CLI

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#165]
An example is here: https://github.com/theislab/sfaira/blob/dev/sfaira/data/dataloaders/loaders/d10_1038_s41586_020_2922_4/human_lung_2020_x_travaglini_001.py. I would suggest the following templates:

If sample_fns is not empty:
```
# import statements 

def load(data_dir, sample_fn, **kwargs):
    fn = os.path.join(data_dir, sample_fn)   # adapt file name if necessary or add additional file names.
    # Prepare adata here.
    return adata
```
else:
```
# import statements 

def load(data_dir, **kwargs):
    fn = os.path.join(data_dir, "some name")   # adapt file name if necessary or add additional file names.
    # Prepare adata here.
    return adata
```

**Comment by Zethson** [comment]
@davidsebfischer So we will just have two types of templates from now on (both yaml based ofc)
1. Several dataloaders -> sample_fns won't be empty
2. Single dataloader -> sample_fns won't exist/be empty

We had 4 earlier

**Comment by davidsebfischer** [comment]
Yes, I simplified this. Technically these two are even the same as the second one also receives `sample_fn=None` in kwargs but I'd like to hide this to not confuse users.

**Comment by davidsebfischer** [comment]
If you think we should move it to one (it would have to be the first one then) I'd also be fine with that though.
