### ISSUE TITLE
optional free text description of data in study

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#180]
Idea: Allow for an entirely free text `.txt` describing data presented in the study. This could mention potential issues with cell type annotation, cell filtering choices, meta data that we do not capture yet, relevant links for potentially disputet annotation etc.
This would just have the same name as the folder and would only be created if there is actually content in there.
It might be a useful replacement of comments in constructor code that we will not be able to maintain if YAMLs are used and could help get people up to speed if they revisit this data set.
To support this, we would just need to put the option to create it into the CLI and document this option in the docs.

**Comment by Zethson** [comment]
So what you want is that the user gets asked whether he wants to add free text and if so he enters it and a .txt file gets created?

**Comment by davidsebfischer** [comment]
In the CLI I would just ask for yes/no, with empty file creation if yes, and then they can use their text editors to put in stuff in whatever format works for them with bullet points etc?

**Comment by le-ander** [comment]
+1 for this feature!

**Comment by Zethson** [comment]
Fine with me, will do

**Comment by Zethson** [comment]
https://github.com/theislab/sfaira/pull/182/commits/a26758c52b4ec096d23070d6e4b38e528a0b55cb
