### ISSUE TITLE
metadata in streamlined adata objects

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#183]
@davidsebfischer would it make sense to somehow define the metadata that is preserved during streamlining in a file in sfaira.consts? (or maybe just preserve all fields listed in AdataIdsSfaira?)

feels like this should not be manually defined in the steramlining function:

https://github.com/theislab/sfaira/blob/2b15f0b5c4e24d41f80580eb03b10b5370903d5c/sfaira/data/base/dataset.py#L669-L700

**Comment by davidsebfischer** [comment]
Yes good point, originally this was intended to be facilitated by containers in here, https://github.com/theislab/sfaira/blob/dev/sfaira/consts/meta_data_files.py, we could make use of these more again!
