### ISSUE TITLE
_celltype_universe

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#185]
should this say `if not self._celltype_universe:`?

https://github.com/theislab/sfaira/blob/49cb5fc764c6f9bb929e9bf0559ff620361487f5/sfaira/data/base/dataset.py#L1857

I can't find any other place where this is set. So the content of the if statement seem inaccessible the way it's written right now?

**Comment by le-ander** [comment]
fixed in 412c328ef98610fbb0383aa6f9f0bf67b8fa35cd

**Comment by davidsebfischer** [comment]
Yes also saw this yesterday!
