### ISSUE TITLE
[Windows] RepositoryNotFound error on sfaira create-dataloader

### ISSUE THREAD

**Issue by Abdul-Moeed** [theislab/sfaira#190]
Path issue on Windows. Traceback
`│ D:\Box\Programs\Anaconda\lib\site-packages\sfaira-0.2.1+180.gb6d1b50.dirty-py3.7.egg\sfaira\commands\create_dataloader.py:53 in create_dataloader                                                    │
│                                                                                                                                                                                                      │
│    50 │   │   """                                                                                                                                                                                    │
│    51 │   │   self._prompt_dataloader_template()                                                                                                                                                     │
│    52 │   │   self._prompt_dataloader_configuration()                                                                                                                                                │
│ >  53 │   │   self._create_dataloader_template()                                                                                                                                                     │
│    54 │                                                                                                                                                                                              │
│    55 │   def _prompt_dataloader_template(self) -> None:                                                                                                                                             │
│    56 │   │   """                                                                                                                                                                                    │
│                                                                                                                                                                                                      │
│ D:\Box\Programs\Anaconda\lib\site-packages\sfaira-0.2.1+180.gb6d1b50.dirty-py3.7.egg\sfaira\commands\create_dataloader.py:155 in _create_dataloader_template                                         │
│                                                                                                                                                                                                      │
│   152 │   │   cookiecutter(f'{template_path}',                                                                                                                                                       │
│   153 │   │   │   │   │    no_input=True,                                                                                                                                                            │
│   154 │   │   │   │   │    overwrite_if_exists=True,                                                                                                                                                 │
│ > 155 │   │   │   │   │    extra_context=self._template_attributes_to_dict())                                                                                                                        │
│                                                                                                                                                                                                      │
│ D:\Box\Programs\Anaconda\lib\site-packages\cookiecutter\main.py:74 in cookiecutter                                                                                                                   │
│                                                                                                                                                                                                      │
│    71 │   │   checkout=checkout,                                                                                                                                                                     │
│    72 │   │   no_input=no_input,                                                                                                                                                                     │
│    73 │   │   password=password,                                                                                                                                                                     │
│ >  74 │   │   directory=directory,                                                                                                                                                                   │
│    75 │   )                                                                                                                                                                                          │
│    76 │                                                                                                                                                                                              │
│    77 │   template_name = os.path.basename(os.path.abspath(repo_dir))                                                                                                                                │
│                                                                                                                                                                                                      │
│ D:\Box\Programs\Anaconda\lib\site-packages\cookiecutter\repository.py:133 in determine_repo_dir                                                                                                      │
│                                                                                                                                                                                                      │
│   130 │                                                                                                                                                                                              │
│   131 │   raise RepositoryNotFound(                                                                                                                                                                  │
│   132 │   │   'A valid repository for "{}" could not be found in the following '                                                                                                                     │
│ > 133 │   │   'locations:\n{}'.format(template, '\n'.join(repository_candidates))                                                                                                                    │
│   134 │   )                                                                                                                                                                                          │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RepositoryNotFound: A valid repository for `

**Comment by Zethson** [comment]
@Abdul-Moeed was this fixed in your latest PR?

**Comment by Abdul-Moeed** [comment]
Yes!
