### ISSUE TITLE
change default data matrix format to lil

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#198]
When collapsing gene-wise counts, we get these warnings a lot:
```
[...]scipy/sparse/_index.py:126: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)
```
We could just turn all matrices into lil here https://github.com/theislab/sfaira/blob/95df92e7b0635e2bf9e222607df8a79dd7ef68b6/sfaira/data/base/dataset.py#L386?

**Comment by davidsebfischer** [comment]
@le-ander

**Comment by le-ander** [comment]
if conversion to and from lil is efficient, then this is a definite yes!
(I'm pretty sure about the latter, not sure about to_lil)

**Comment by davidsebfischer** [comment]
anndata did not support lil in all steps so I dropped using this.
