### ISSUE TITLE
loosing .uns metadata when concatenating

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#212]
I was facing some problems with metadata in .uns, when I realised that we currently don't seem to have any mechanism that automatically transfers uns labels into obs before concatenating adatas when calling DatasetGroup.adata

I'm wondering whether we should just by default move all uns to obs before concatenating adatas. Couldn't we just add a call to `self._set_metadata_in_adata(allow_uns=False)` before this line:
https://github.com/theislab/sfaira/blob/58aadc6f9678f83f37587e1eceb6aaea99faa717/sfaira/data/base/dataset_group.py#L318

what do you think @davidsebfischer ?

**Comment by davidsebfischer** [comment]
I think `streamline` would be better for that? We could just call streamline inside of `.adata` before concatenating.

**Comment by le-ander** [comment]
we do call streamline a couple of lines up. however streamline doesn't move uns items to obs as far as I can see right now

**Comment by davidsebfischer** [comment]
> we do call streamline a couple of lines up. however streamline doesn't move uns items to obs as far as I can see right now

We can just make that optional for `format == "sfaira"` too and use it in concatenate?

**Comment by le-ander** [comment]
like have another input argument for .streamline(format=="sfaira", allow_uns=False)?

**Comment by le-ander** [comment]
would the cellxgene streamlining respect this attribute as well or should this always be false for cellxgene streamlining?

**Comment by davidsebfischer** [comment]
Cellxgene streamlining needs allow_uns=False because the cellxgene object format is narrowly defined on this. I would not optimise this interface too much though because they might be merged in the future: https://github.com/theislab/sfaira/issues/200.
