### ISSUE TITLE
Broken tutorial links in docs

### ISSUE THREAD

**Issue by ggabernet** [theislab/sfaira#227]
Hi, 
thanks for developing the sfaira tool, it looks really promising!

I wanted to try it out but realized that the tutorial links here are broken: https://sfaira.readthedocs.io/en/latest/tutorials.html

**Comment by Zethson** [comment]
Dear @ggabernet

We are currently still working on Sfaira and will release a new version soon with updated tutorials.
I'll ping you and @KevinMenden when it happens ;)

**Comment by ggabernet** [comment]
sounds good, thanks!

**Comment by Zethson** [comment]
https://github.com/theislab/sfaira_tutorials

And solved in private communication.
