### ISSUE TITLE
Circularity in dataloading

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#228]
When instantiating sfaira.data.Universe() with a meta_path set, sfaira will crash if it encounters a dataset that does not have a doi set (circularity error). This is because self._doi being none, triggers sfaira to check metadata for this field, for this it will however require the doi, when self.meta_path is set which leads to an infinite loop:

https://github.com/theislab/sfaira/blob/56a2c1ec72941dd855377b7e99b0818088dba8b5/sfaira/data/base/dataset.py#L1193

**Comment by davidsebfischer** [comment]
Which data set does not have a DOI? We should catch this loop but DOI will be required for all data sets and should be there for all right now, too.

**Comment by le-ander** [comment]
not sure if there is one without a doi right now, just saw this and though we should catch this better
