### ISSUE TITLE
improvements for data cli

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#230]
- [ ] make sure that error is raised if mandatory data is missing
- [x] make **required** fields more clear (in rst -> link to bottom of page)
- [x] take **clean** out of instructions
- [x] rename lint stuff into **validate**: validate lint and test load .adata
- [x] remove annotate frmo **test** function
- [ ] use more try except statements
- [x] add graphical schema: create -> validates -> annotate -> test

**Comment by Zethson** [comment]
Draft for the graphical schema:

![image](https://user-images.githubusercontent.com/21954664/117845386-c6744a00-b280-11eb-9d86-8c47132a3949.png)

Fine like this? Don't want to spend too much time on it.

**Comment by davidsebfischer** [comment]
YES!
