### ISSUE TITLE
allow custom ontologies in cell type predictor models

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#253]
Require custom ontologies to still be fed through `OntologyObo()`:

- [x] Allow cell type ontology to be replaced in cell type predictor estimator class.
- [x] Allow custom ontology in model topology
- [x] Allow custom feature space in model topology

**Comment by LisaSikkema** [comment]
error when trying to load a custom .obo file into an OntologyObo class:
```python
ref_obo = sfaira.versions.metadata.base.OntologyObo(file_path)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-a26c95cf79bb> in <module>
----> 1 ref_obo = sfaira.versions.metadata.base.OntologyObo(file_path)

TypeError: Can't instantiate abstract class OntologyObo with abstract methods synonym_node_properties
```

**Comment by davidsebfischer** [comment]
**1. Write a custom obo for your ontology**
Here is an example file:
`custom.obo`:
```
format-version: 1.2
ontology: custom

[Term]
id: MYONTO:01
name: Name1

[Term]
id: MYONTO:02
name: Name2
is_a: MYONTO:01

[Term]
id: MYONTO:03
name: Name3
is_a: MYONTO:01
```

**2. Instanitate custom Obo container**
`obo_container = OntologyOboCustom(obo=fn)` with your obo

**3. Prepare count matrix**
Throughout this process, keep data in an AnnData instance with the custom feature space (e.g. embedding) in `.X`.
Add embedding dimension names (dim0-dim49 or sth like this) into .var in the column "ensembl".

**4 Prepare an accompanying feature space object**
Make a pandas data frame based ont hese features with the following cols

```
Table characterising feature space. Must be a data frame with 3 columns:
        
            - "gene_name": Name of features.
            - "gene_id": ID of features, can be the same as values of "gene_name"
            - "gene_biotype": Types of features, can be arbitrary like "embedding"
```
Pack this custom feature space into a class: 

```
gc = sfaira.versions.genomes.CustomFeatureContainer(tab)
```

**5 Instantiate a model topology conainer**

```
tc = TopologyContainer(topology={
        "model_type": "mlp",
        "input": {
            "genome": "custom",
            "genes": ["biotype", "embedding"],  # TODO if you didnt choose "embedding" for biotype above, put sth else here
        },
        "output": {
            "cl": "some_name_for_your ontology",  # TODO
            "targets": [],  # list of nodes that are leaves of your DAG
        },
        "hyper_parameters": {.  # TODO adjust these hyperparameters depedning on how you want the MLP to look like
            "units": [],
            "activation": None,
            "use_bias": True,
            "l1_coef": 0.,
            "l2_coef": 0.,
            "kernel_initializer": 'glorot_uniform',
            "bias_initializer": 'zeros',
            "bias_regularizer": None,
            "activity_regularizer": None,
            "kernel_constraint": None,
            "bias_constraint": None
        }
}, topology_id="0.0.1)
```
Note on targets: if you want to get all leaves of your tree, just take the list that is output by `.leaves` of your instance of `OntologyOboCustom`: `obo_container.leaves`

**6 Instantiate the estimator class**
```
estim = EstimatorKerasCelltype(
    data=adata,
    model_id="some_name_for_the_model",
    model_topology=tc,
    celltype_ontology=obo_container,
)
```
For more informations on this estimator object, read the doc strings of the class and its methods

**7 Train model**
```
estim.train()
```
Use functions of `.train()` as described in its doc strings.

**8 Use the model**
Check out model methods of the estimator instance such as `.predict*` and `.evaluate*`.

This workflow is also replicated in the unit test `sfaira/unit_tests/estimators/test_estimator/test_for_fatal_mlp_custom()`

**Comment by davidsebfischer** [comment]
@LisaSikkema this is unit tested so should be largely ready to go, PR is linked on which this is based, let me know if you encounter further issues!
