### ISSUE TITLE
Sfaira field names in _convert_and_set_var_names

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#32]
I'm a bit unsure why we would use attributes of ADATA_IDS_SFAIRA to define symbol_col= and ensembl_col= in _convert_and_set_var_names() these should always be independent, no?

https://github.com/theislab/sfaira/blob/273d7b6688f34fc72db1650ef29c61982ccbfa34/sfaira/data/human/kidney/human_kidney_2020_10x_liao_001.py#L116

**Comment by davidsebfischer** [comment]
Yes true, these we could keep as strings there!

**Comment by le-ander** [comment]
I guess the only instance where we could have ADATA_IDS_SFAIRA fields in _convert_and_set_var_names() would be when we have just created a new var column of the name ADATA_IDS_SFAIRA.... in the dataloader above
