### ISSUE TITLE
CLI documentation and path handling

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#321]
**Describe the bug**
- [x] Running `sfaira create-dataloader` created the data loader in the top level directoy of the sfaira clone, not under `sfaira/data/dataloaders/loaders/` as described in step 3
- [x] Let s use the same path argument definition for annotate and for test, right now they are different, test requires absolute paths. I would go for `sfaira/data/dataloaders/loaders/`default for `path`
- [x] Can `sfaira/unit_tests/template_data/` be the default of `test-data` throughout, eg. in `annotate-dataloader`? @le-ander Also relates to where the data loder directory is during generation, ie in place in the clone or somewhere else.
- [x] validate, annotate and test use different ways of supplying the DOI; can we use the same in all of them? The individual yamls discovered in validate with the `*yaml` operator could also be discovered with `os.listdir`. I like supplying DOI as a separate argument, ie how it works in annotate, makes it very clear and also easy to copy paste the command (slightly better than the questionaire in test I think?), we could optionally fall back to the questionaire in all of them?
- [x] take special characters and white spaces out of meta data items that are used to assemble loader file names, e.g. `human_lamina propria of mucosa of colon_2019_10x technology_Kinchen_001.yaml` should not contain white spaces, here "lamina propria of mucosa of colon" is a meta data label, similar "10x technology". In sfaira, ie use `data/base/dataset:clean_string()` for this a lot, maybe you can relay all string conversions to one (maybe this) function.
- [x] Can we move the data loader unit test out of the unit_module and into the CLI module? I would be ok with not running it with pytest but just as standard function. I find the current format slightly confusing both on the side of reading the CLI and on reading unit tests, this is of course an effect of how we developed this. If we want, we can still later add unit tests for the entre CLI.
- [x] The docs documentation step 9) states `# sfaira annotate <path>`` TODO` but this should be `sfaira annotate-dataloader sfaira/data/dataloaders/loaders --doi=<DOI> --test-data=sfaira/unit_tests/template_data/`
- [x] In step 11, update `# sfaira test-dataloader <path>`` TODO` 

What works for me right now:
- `sfaira annotate-dataloader sfaira/data/dataloaders/loaders --doi=<DOI> --test-data=sfaira/unit_tests/template_data/`
- `sfaira annotate-dataloader sfaira/data/dataloaders/loaders/ --doi=<DOI> --test-data=sfaira/unit_tests/template_data/`
- `sfaira test-dataloader <full path to sfaira top level directory> --test-data=<full path to sfaira top level directory/sfaira/unit_tests/template_data/ --doi=<DOI>`

These point should result in every CLI call to receive the same arguments
- path -> let s rename to `path_loader` (optional, expected in `sfaira/data/dataloaders/loaders/` per default)
- doi (optional -> triggeres questionaire if not given)
- test-data -> let s rename to `path-data` (optional, expected in )

The final interface would then be:
- `sfaira annotate-dataloader [--doi] [--path-data,--path_loader]`
- `sfaira annotate-dataloader [--doi] [--path-data,--path_loader]`
- `sfaira test-dataloader [--doi] [--path-data,--path_loader]`

- [x] Document this in .rst
- [x] Update figure in docs with merged validata & annotate
- [x] add sample source attribute to create-dataloader and make it a required attribure
- [x] make one of gene_id_ensembl_var_key / gene_id_symbols_var_key a required attribute
- [x] rename assay to assay_sc
- [x] add missing fields to yaml templates and document them (see eg. here for all the current fields: https://github.com/theislab/sfaira/blob/bug/cli_documentation/sfaira/data/dataloaders/loaders/d10_1101_2020_10_12_335331/human_blood_2020_10x_hao_001.yaml)
- [x] ask user explicitely if he has celltype annotations and then inform him about whether or not to run annotate-dataloader

I started improving some things here, https://github.com/theislab/sfaira/pull/320, maybe we can settle this issue on that PR. I improved reporting of a number of file not found issues there already, I think if we streamline the paths we have a lot of the hard-to-comprehend issues already addressed.

**Comment by le-ander** [comment]
@davidsebfischer @Zethson quick question:
did we already decide what to do with clean_dataloader and validate-dataloader? The latter is still part of the docs but it's unclear to me why it should be separated from test-dataloader?

If we no longer need them I'd take them out to make things more readable

**Comment by davidsebfischer** [comment]
I do not think that `clean_dataloader` still exists in the CLI, its functionality is also depreceated (we do not want to remove these), so we can remove it from the docs!

**Comment by Zethson** [comment]
> @davidsebfischer @Zethson quick question:
> did we already decide what to do with clean_dataloader and validate-dataloader? The latter is still part of the docs but it's unclear to me why it should be separated from test-dataloader?
> 
> If we no longer need them I'd take them out to make things more readable

IIRC clean-dataloader was something we kept as an option, but would not enforce. Feel free to take it out.
Merging validation & testing is now also fine since annotating is its own step.



> I do not think that `clean_dataloader` still exists in the CLI, its functionality is also depreceated (we do not want to remove these), so we can remove it from the docs!

Just saw. It's still implemented :)

**Comment by le-ander** [comment]
my feeling is that running 4 CLI commands to create a dataloader is not very user friendly but if you guys don't think merging any of these commands makes sense, I guess we can just leave it like it is

**Comment by le-ander** [comment]
>  than it s only create->annotate->test, that s the minimal number of commands here i think
I think I'd prefer that

**Comment by Zethson** [comment]
All right, then let's roll with this :)

**Comment by davidsebfischer** [comment]
We can still keep validate in the CLI but not use it in the documentation? I see cases where people may want to lint something briefly if they are very familiar with this stuff.

**Comment by Zethson** [comment]
> We can still keep validate in the CLI but not use it in the documentation? I see cases where people may want to lint something briefly if they are very familiar with this stuff.

Sure, does not hurt.

Do you want me to update the workflow figure and remove the validate step here? Or "merge" them in the figure?

**Comment by le-ander** [comment]
i think merging them in the figure would be nice!

**Comment by le-ander** [comment]
Hey @Zethson 
I have complete all the main points above to improve the CLI but did not manage to finish a couple of minor things which I have documented as a list at the bottom of the first comment above. Do you think you could take over from here and finish up the open points together with #314 when you're normally back at work again? I'll be back Tuesday next week.
Thanks a lot!
