### ISSUE TITLE
Cell type matched wrongly

### ISSUE THREAD

**Issue by Hrovatin** [theislab/sfaira#337]
When loading sfaira (human pancreas) I have noticed some cell types are matched to ontology wrongly.

Both should be "pancreatic PP cell":
gamma | ['pancreatic endocrine cell']
gamma cell | ['pancreatic endocrine cell']

**Comment by davidsebfischer** [comment]
Thanks @Hrovatin, do you know which data sets in particular?

**Comment by davidsebfischer** [comment]
I found:

- [ ] https://github.com/theislab/sfaira/blob/dab9cb3f6d89dc6c6b52f9ce23c9a7e938e4d91b/sfaira/data/dataloaders/loaders/d10_1016_j_cels_2016_08_011/human_pancreas_2016_indrop_baron_001.tsv#L10 (flagged here https://github.com/theislab/sfaira/blob/dab9cb3f6d89dc6c6b52f9ce23c9a7e938e4d91b/sfaira/data/dataloaders/loaders/d10_1016_j_cels_2016_08_011/human_pancreas_2016_indrop_baron_001.py#L11), need to remove class map too: https://github.com/theislab/sfaira/blob/dab9cb3f6d89dc6c6b52f9ce23c9a7e938e4d91b/sfaira/data/dataloaders/loaders/d10_1016_j_cels_2016_08_011/human_pancreas_2016_indrop_baron_001.py#L35
- [ ] https://github.com/theislab/sfaira/blob/dab9cb3f6d89dc6c6b52f9ce23c9a7e938e4d91b/sfaira/data/dataloaders/loaders/d10_1016_j_cmet_2016_08_020/human_pancreas_2016_smartseq2_segerstolpe_001.tsv (flagged here https://github.com/theislab/sfaira/blob/dab9cb3f6d89dc6c6b52f9ce23c9a7e938e4d91b/sfaira/data/dataloaders/loaders/d10_1016_j_cmet_2016_08_020/human_pancreas_2016_smartseq2_segerstolpe_001.py#L10)

**Comment by davidsebfischer** [comment]
new term: "pancreatic PP cell", "CL:0002275"

**Comment by davidsebfischer** [comment]
PP is a sub term of "pancreatic endocrine cell" (https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0008024&viewMode=PreferredRoots&siblings=false), I think at the time we did not know the exact term because gamma is not annotated in cellontology. Therefore, we chose the umbrella term.

**Comment by Hrovatin** [comment]
Yes, gamma was an old name for Pp cells, but it is still often used in literature.

**Comment by davidsebfischer** [comment]
I won't hard-code it to the semi-automatic matching as this is technically a synonym of the cell type label, ie something that cell ontology takes care of managing and that we simply consume here.

**Comment by davidsebfischer** [comment]
We could ask cellontology to update it though!
