### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by soerenab** [theislab/sfaira#377]
**Describe the bug**
Errors during installation caused by unresolvable requirement conflicts.

**To Reproduce**
I created a new, separate conda environment for each of the installation attempts decribed below with:
```conda create --name=sfaira python=3.9```. I am using conda-forge as this provides better support for apple M1 hardware, see details below.

I have tried installing all installation options listed here: https://sfaira.readthedocs.io/en/latest/installation.html
1. installation via pip: ```pip install sfaira --no-cache-dir```
2. cloning the github repository and installing with ```pip install -e . --no-cache-dir```
3. The above commands raise many errors, in particular tensorflow cannot be installed. So I just installed tensorflow prior to installing sfaira and repeated the installation via pip, i.e. ```conda install tensorflow``` then ```pip install sfaira --no-cache-dir```. 

I have attached logfiles for outputs from the installation processes 1. and 2. (for 3. the log file seems to be too large) to this issues in two separate files. I think the underlying problem is actually not tensorflow but conflicting version requirements about numpy (I think numba supports only 1.17 < numpy < 1.21 but some other packages require numpy > 1.21. This is only my best guess about the problems though, cannot say with certainty.

**Expected behavior**
Installation without running into errors or description of how to manually install the correct versions of required packages so that sfaira can be pip installed without installing its dependencies (```--no-dependencies```).

**System [please complete the following information]:**
 - OS: macOS Big Sur, Version 11.5.1 (20G80)
 - Language Version: Python 3.9
 - Virtual environment: conda-forge 4.10.3, see perhaps: https://conda-forge.org/

**Additional context**
[sfaira_git.txt](https://github.com/theislab/sfaira/files/7217056/sfaira_git.txt)
[sfaira_pip.txt](https://github.com/theislab/sfaira/files/7217057/sfaira_pip.txt)

**Comment by davidsebfischer** [comment]
This is most likely related to the installation of linear algebra dependencies on apple M1 chips, we will assemble a separate installation instruction for that.

**Comment by soerenab** [comment]
Just to avoid duplicate work: I will look into this now and keep you updated.

**Comment by davidsebfischer** [comment]
This might be a helpful starting point: https://github.com/scipy/scipy/issues/13409

**Comment by soerenab** [comment]
It seems that I have now successfully installed sfaira and its dependencies. This statement comes with a bit of caution as I have so far only tested the installation by running ```sfaira create-dataloader``` but this worked without errors.

For completeness, I am on macOS Big Sur Version 11.5.1 (20G80) on M1 hardware and I am using conda-forge (4.10.3) and pip (21.2.4) to manage python packages. I am using conda-forge rather than regular miniconda as it (currently) provides better support for M1 hardware, see [https://conda-forge.org/](https://conda-forge.org/).

Some best guesses as to why the installation does not work out of the box:
- Requirement version conflicts for numpy. In particular, when installing numba via conda, it requires numpy<1.21, however, cellxgene_schema (officially) requires [numpy==1.21.2](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/requirements.txt). My solution here was to install numba first (which installs a compatible version of numpy) and to then install cellxgene without its dependencies, which seems to work. Interestingly, ```pip install cellxgene_schema --no-deps``` installs version ```2.0.0``` but when installing ```pip install sfaira``` afterwards, cellxgene_schema is downgraded to ```0.2.0```, not sure if this is a bug/type or an actual requirement though. 

- ```pip install anndata``` is unable to build dependencies that are not already satisfied.

The solution that seems to work for me was to manually install as many dependencies as possible prior to installing cellxgene_schema, anndata, scanpy and sfaira. In particular:

1. Prior to any installation, I am setting up a new conda environment with ```conda create --name=sfaira python=3.9``` and activate it once it is installed: ```conda activate sfaira```.

2. Install as many packages as possible via conda: ```conda install numba tensorflow wheel click cython seaborn scikit-learn statsmodels pytables loompy natsort packaging xlrd=1 boltons zarr matplotlib openpyxl pyyaml pytest dask docutils ipython networkx pyarrow tqdm requests versioneer rich questionary flatten-dict conda-forge python-igraph leidenalg``` Note that you want to install networkx >=2.6.3 as you will otherwise get a runtime error saying that "gcd" cannot be imported from fractions, see https://github.com/ewels/MultiQC/issues/1413](https://github.com/ewels/MultiQC/issues/1413) . The above command should already take care of this (check via ```conda list networkx```), otherwise upgrade via ```conda upgrade networkx```.

3. Install remaining dependencies via pip: ```pip install owlready2 fuzzywuzzy obonet python-levenshtein switchlang cookiecutter crossref_commons```

4. Install anndata and cellxgene-schema without their dependencies to avoid version conflicts, e.g. of numpy ```pip install anndata cellxgene-schema --no-deps```

5. ```pip install scanpy``` (this installs some remaining dependencies.)

6. ```pip install sfaira```
