### ISSUE TITLE
invalid path for CLI

### ISSUE THREAD

**Issue by M0hammadL** [theislab/sfaira#388]
**Describe the bug**
The path provided for data loader are replaced by default or sth completely different from the input 

**To Reproduce**
enter 
`sfaira test-dataloader --doi 10_1038_nbt_4042--path-loader /Users/mohammad.lotfollahi/PycharmProjects/sfaira/sfaira/data/dataloaders/loaders/d10_1038_nbt_4042 --path-data /Users/mohammad.lotfollahi/PycharmProjects/sfaira/data/kang_seurat.h5ad 
`
and the error is : 

`Error: Invalid value for '--path-loader': Path 'sfaira/data/dataloaders/loaders/' does not exist`

**Expected behavior**
it should look in to provided path not the default

**System [please complete the following information]:**
 - OS: Big Sur
 - Language Version: 3.7.11
 - Virtual environment: conda

**Comment by Zethson** [comment]
@M0hammadL accidentally missed a space before `--path-loader`
