### ISSUE TITLE
Clarify DOI input format in data contribution docs

### ISSUE THREAD

**Issue by Zethson** [theislab/sfaira#389]
@MO-L used the sfaira representation as input to the test-dataloader command. The correct input though is the normal DOI representation because sfaira transforms it on the fly when testing.

Should be clarified in the docs.

**Comment by davidsebfischer** [comment]
Could we catch this error in the CLI input via an error? We can just flag input `"d*"`.

**Comment by Zethson** [comment]
Sure. Will do Monday, 04 October 2021, 09:34AM +02:00 from David S. Fischer  ***@***.*** :
