### ISSUE TITLE
SummarizeGridsearchEmbedding().best_model_embedding() does not handle gaussian metrics

### ISSUE THREAD

**Issue by Abdul-Moeed** [theislab/sfaira#4]
Issue on #3  
The summary table contains gaussian metrics such as `val_custom_negll_gaussian` but `best_model_embedding() `does not check for those and throws an error.

**Comment by le-ander** [comment]
can you post the traceback here abdul? (always good to have this for issues)

**Comment by le-ander** [comment]
I have fixed this for further gridsearches.
@Abdul-Moeed as a workaroung to find the best model from those gridsearches where you get this error, you can temporarily locally replace line 261 (`                or metric_select.endswith('negll') \`) with the following:
```python
                or 'negll' in metric_select \
```
