### ISSUE TITLE
YAML data set group options

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#403]
We can describe data set-wise attributes in the YAML and this is supported by the CLI:
`    
organ:
        A: "blood"
        B: "blood"
        B: "blood"
`
The summary version is often preferable so that the yaml does not become too large:
`    
organ:  "blood"
`
Can we find a way to only autogenerate the data set-wise options list in the CLI when it s necessary? Ie for a multidataset template, ask for attributes that are data set specific or so? It easy to add another list in later manually but deleting all of them together might be a bit off putting for users.

**Comment by Zethson** [comment]
How would you envision this to work? Should we ask for every attribute whether it is dataset specific? I am not sure what the nicest user experience would be.

**Comment by davidsebfischer** [comment]
> How would you envision this to work? Should we ask for every attribute whether it is dataset specific? I am not sure what the nicest user experience would be.

Usually, if one opts for this data loader scenario, the data sets are very similarly structured (otherwise load function can also not be shared). So we should expect most of the attributes to be global. How about:

1) We do not open a list for attributes that are not set.
2) We give a choice between (skip, global, dataset-wise) to be selected with arrow keys for each attribute? That way, one could still easily go through empty fields by clicking enter a lot, this works well know i think, but now, if you want tot write sth, you first have to decide whether its global or data set wise.

Side remark:
- [ ] Can we switch fields that were not set to empty rather than "NA"? Right now, sample_source, organ and assay_sc default to "NA", we are better  of with empty here I think as these could actually be left empty.

**Comment by Zethson** [comment]
All right. ETA 2 weeks or so.
