### ISSUE TITLE
Bug SummThe TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine. Abortedary

### ISSUE THREAD

**Issue by bio-la** [theislab/sfaira#414]
**Describe the bug**
pip installed something and this must have messed up my sfaira env. pulled from main and reinstalling but have this error now

**To Reproduce**
git checkout main
git pull
pip install -e .
git checkout -b fc_dloader
sfaira create-dataloader --doi 10.1016/j.cell.2020.10.037 --path_data /home/icb/fabiola.curion/devel/downloads/su_et_al_gex_raw.h5ad
The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
Aborted

**Expected behavior**
start the command line dataloader creator

**System [please complete the following information]:**
Conda env python 3.8 

**Additional context**

**Comment by davidsebfischer** [comment]
This is an issue with the tensorflow installation in the python environment.
