### ISSUE TITLE
Performance improvement: sfaira.data.store.io_data.read_dao

### ISSUE THREAD

**Issue by felix0097** [theislab/sfaira#416]
The `sfaira.data.store.io_data.read_dao` function spends most of it's time reading in a pickle file: 
https://github.com/theislab/sfaira/blob/aeaa60ff128046b7564aa9cccd6293a9300e5a31/sfaira/data/store/io_dao.py#L117

Maybe there is a more efficient way to read in the necessary data.

Here's a screenshot of the profiler output:

![profile-load-store-dao](https://user-images.githubusercontent.com/47145207/142904747-06d8d4e2-4cbc-4872-abe1-2cd32edaed5f.png)

**Comment by davidsebfischer** [comment]
The .uns in stores are very regularized, there are either numbers, strings or lists thereof in there. We could represent it as a table or as a yaml. csv has the advantage that we could easily interface with cloud-backed data representations such as from parquet (see also .obs), that should be very fast to initialise as well and allows lazy reading which could be advantageous.

**Comment by felix0097** [comment]
Just checked - the profiler output does not really make much sense cause the `uns` data files are super small, so should be fast to read in. 

Ran pyinstrument profiler instead of the cProfile and things look much more sensible now: 
![image](https://user-images.githubusercontent.com/47145207/143551703-977aee0d-ef1c-4758-81d0-be39ee1e9bc0.png)

Looking at this, it doesn't make much sense to change the current implementation away from using pickle.

**Comment by davidsebfischer** [comment]
Thanks! Will still make sense to allow for remote (eg S3 or so) backed formats in the future, which pickle is not I think, but good to know that run time is not an issue.

**Comment by davidsebfischer** [comment]
Do you know what the 407sec on `self` are?

**Comment by felix0097** [comment]
According to this it's the time spent in the function that's not attributable to any child function: https://github.com/joerick/pyinstrument/issues/111#issuecomment-736790024

**Comment by felix0097** [comment]
but not sure whether that makes sense. Cause there is not much happening in the function except for calling other functions

**Comment by davidsebfischer** [comment]
> but not sure whether that makes sense. Cause there is not much happening in the function except for calling other functions

ok, let s leave it open and come back to it later again!

**Comment by felix0097** [comment]
This is fixed now with the above mentioned pull request. Issue was that the Anndata OverloadedDict saved lots of unnecessary data which made the saved pickle files extremely large.
