### ISSUE TITLE
cached loading code

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#48]
I cannot see any code for actually loading a cached dataset in _load_cached()
am I missing something?

**Comment by le-ander** [comment]
also I think the funciton breaks if self.cache_path is not set. or is this handled somewehre outside?

**Comment by davidsebfischer** [comment]
- Loading code was missing, I added this now.
- I am throwing explicit caching errors now if these functionalities are used and cache_path is not set. The data zoo can still be used without caching (ie if data is only ever loaded raw), but I think that cache_path should be almost always set for our puropses.

**Comment by le-ander** [comment]
Cool, thanks!
Some thoughts on that:

https://github.com/theislab/sfaira/blob/8e8756b074834a1370d1fec79e18f53462796e74/sfaira/data/base.py#L149-L153
This will throw an error if self.cache_path is None

https://github.com/theislab/sfaira/blob/8e8756b074834a1370d1fec79e18f53462796e74/sfaira/data/base.py#L159
Should we really throw an error if load_raw=False and the cached file is not found? I'd rather have interpreted load_raw as "don't use the cache file if I set this to true. When setting it to false, just load the raw one anyway if you cannot find the cached file"

**Comment by davidsebfischer** [comment]
I implemented what you suggested, @le-ander!
