### ISSUE TITLE
make non DOI data sets identifiable

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#57]
This applies to all data sets currently in `d_nan`.

**Comment by Zethson** [comment]
Which solution do you envision? Should we just generate a unique hash?
MD5 for all files and then generate a hash from that?

**Comment by davidsebfischer** [comment]
I'd prefer a unique scheme based on names, I would consider MD5 as an orthogonal mechanism that could be applied to all data sets. Essentially we can use the same scheme as before and just need to replace doi with a constant string for example.

**Comment by davidsebfischer** [comment]
@Zethson let's also decide this now? how about we structure this by source, e.g. we could create "no_doi_10x_genomics" as a DOI equivalent, meaning that their websites identifies these data sets? If we find more such sources, we could add them similarly.

**Comment by Zethson** [comment]
Yeah, that sounds reasonable. I like that it will result in a nice grouping.
