### ISSUE TITLE
dataset (group) subsetting

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#60]
Currently we have `subset()`and  methods on these classes. `subset()` is effectively based on dataset-wise attributed right now. `subset_organ()` is an example of a cell-wise subsetting method. Now, we have however many more attributed that can be cell rather than dataset-wise, let's generalise this method, too. Ie rename and generalise the interface to attr and value like in subset. I would call it `subset_cells()`.

**Comment by le-ander** [comment]
Sounds good. Does this just apply to the mixed datasets or do you rather want me to generalise this method so it fits all subsetting usecases?

**Comment by davidsebfischer** [comment]
The latter, generalise to cell subsetting and then apply this to the mixed data loaders. Let me know if you need help!
