### ISSUE TITLE
CLI fails on init using Python 3.9

### ISSUE THREAD

**Issue by falexwolf** [theislab/sfaira#638]
**Describe the bug**
Installing sfaira via pip and trying to output help gives this error message:
```
(base) % sfaira -h
zsh: illegal hardware instruction  sfaira -h
(base) % /opt/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
``` 
I assume it's due to Python 3.9, will confirm by checking with a 3.8 environment a bit later. Compatibility with 3.9 would still be great! 😅 

**System:**
 - OS: macOS 12.0.1
 - Language Version: Python 3.9
 - Virtual environment: Conda

**Comment by davidsebfischer** [comment]
Hi @falexwolf! `illegal hardware instruction` is usually what you get in the context of sfaira if your machine does not support tensorflow at all which causes the python session to crash. Not sure about 3.9 I have been using 3.8 recently.

**Comment by le-ander** [comment]
I have not had any problems with python 3.9 and sfaira so far. Should be all running.

As David said, we see this error with CPUs that do not support AVX (as sfaira imports tensorflow which crashes on non AVX-CPUs). CPUs have been supporting this for many years though, so not sure if this applies here.

**Comment by le-ander** [comment]
Could this be an issue with tensorflow on an M1 machine? 🤔

**Comment by falexwolf** [comment]
Yes, I have an M1. I guess that's it. Is there any workaround?

**Comment by le-ander** [comment]
I have never played with an M1 myself, however all you need to do is to get tensorflow to run in that conda environment first. I'm sure there are plenty of tutorials for that online. once tensorflow is installed and running, you can try installing sfaira. should not crash anymore then I guess.

**Comment by davidsebfischer** [comment]
Yup, this preinstallation was successful here https://github.com/theislab/sfaira/issues/377, I would imagine it is easier now though. We are also going to make tf an optional dependency fairly soon, we are wrapping up some improvements in the `data` submodule right now and will then make some changes to the `models` submodule (where this is imported).
