### ISSUE TITLE
Automated dataset download

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#65]
@davidsebfischer I'll give this a go and see if there are any hurdles still for this.

**Comment by davidsebfischer** [comment]
It would be nice if we use automated study / data loader discovery as we do during module loading right now here: https://github.com/theislab/sfaira/blob/human_data_loader_fixes/sfaira/data/dataloaders/loaders/super_group.py. So maybe we can write a similar class, create a folder in a give directory for each doi with the same name as the the module in `loaders/` and then invoke the `Dataset.download()` function for each dataset in this doi group (and the loaders can again be discovered as above). `Dataset.download()` we still need to write.

**Comment by le-ander** [comment]
I might be missing something, but can we not just check upon loading of each dataset check whether the referenced file exists and if not, download it? So basically make a call to Dataset.donload() part of Dataset.load() ?

**Comment by le-ander** [comment]
Also, what would be you suggestion for cases like this one? Can't really automate downloads here:
https://github.com/theislab/sfaira/blob/81f1e599581156f5f1584c4b2e39b529294dca76/sfaira/data/dataloaders/loaders/d10_1038_s41586_020_2922_4/human_lung_2020_10x_travaglini_001.py#L12-15

**Comment by davidsebfischer** [comment]
> I might be missing something, but can we not just check upon loading of each dataset check whether the referenced file exists and if not, download it? So basically make a call to Dataset.donload() part of Dataset.load() ?

That would imply that everybody wants to have the full set of all data sets if they run load() on a predefined group, I do not think this is always the case. Moreover, this should not be done in parallel jobs or similar that might all run load(), so I would really keep this separate.

> Also, what would be you suggestion for cases like this one? Can't really automate downloads here:

I would set `.download = "login" and we will then report to the user that they have to take additional action, similar with "private" meta data.

**Comment by davidsebfischer** [comment]
This is a python client right? We could abstract this code into a _snypase_download() or so and allow the user to set the access credentials before loading. This could also work for other clients, in this case it would be a very clean solution. You could check in .download() if self.download suggests that this is asynapse file and call the _snypase_download() with the corresponding items, which could be stored in self.download for example.

**Comment by le-ander** [comment]
> That would imply that everybody wants to have the full set of all data sets if they run load() on a predefined group, I do not think this is always the case. Moreover, this should not be done in parallel jobs or similar that might all run load(), so I would really keep this separate.

Hm, what would such a predefined group be? And if we want to be this granular with choosing what datasets to download, how would we achieve this in the 'automated dataloader discovery' setting you're proposing?

> Dataset.download() we still need to write.

This would be a dataset-specific function right? probably not that much in common to make this something universal that is inherited form the baseclass?

**Comment by davidsebfischer** [comment]
> > That would imply that everybody wants to have the full set of all data sets if they run load() on a predefined group, I do not think this is always the case. Moreover, this should not be done in parallel jobs or similar that might all run load(), so I would really keep this separate.
> 
> Hm, what would such a predefined group be? And if we want to be this granular with choosing what datasets to download, how would we achieve this in the 'automated dataloader discovery' setting you're proposing?

A predefined group is a DatasetGroup or DatasetSuperGroup instance. 'automated dataloader discovery' is the grabbing of data loaders from study-centric modules. This we just do to establish a SuperGroup that contains all data sets (this does not change the way we think about doing group operations on data set!), a user would then subset this group to all data sets they care about, e.g. all lung data sets after 2018, and would then invoke download on this subsetted DatasetGroup or DatasetSuperGroup instance. Importantly, this does not affect how we have to write the download function, we just need 1) Dataset.download(), 2) DatasetGroup.download() which calls Dataset.download() and 3) DatasetSuperGroup.download() which calls DatasetGroup.download().
 
> > Dataset.download() we still need to write.
> 
> This would be a dataset-specific function right? probably not that much in common to make this something universal that is inherited form the baseclass?

I think all of our downloads are basic downloads that can be handled with urllib (except for the synapse case above), so given the download urls this is entirly generalisable as far I see it. Discovery of interfaces like synapse is also possible based on the URL. I do not think that we need any data set specific code here, we should not require this either if possible.

**Comment by le-ander** [comment]
Thanks a lot for the clarification!
Would we handle download of database-related datasets (eg. cellxgene database) separate from all this?

**Comment by davidsebfischer** [comment]
> Would we handle download of database-related datasets (eg. cellxgene database) separate from all this?

Yes! This is only about retrieval of declared URLs.
