### ISSUE TITLE
The python-Levenshtein is no longer maintained, please update the dependency

### ISSUE THREAD

**Issue by subercui** [theislab/sfaira#667]
**Is your feature request related to a problem? Please describe.**
The `python-Levenshtein` package is no longer maintained. Including it in the dependencies creates potential installation issues. Personally, I can't install it using pip with python 3.9, Ubuntu 18.04, and I found this is a common issue.

**Describe the solution you'd like**
There are two active forks of `python-Levenshtein`, https://pypi.org/project/Levenshtein/ and https://pypi.org/project/python-Levenshtein-wheels/ . It could be a simple solution to just replace the dependency with either one.

**Additional context**

**Comment by le-ander** [comment]
this is now fixed, thanks!
