### ISSUE TITLE
Clean up raw loading code in dataset doc strings

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#67]
Remove loading code in classes in which this code was moved to `_load()`, such was here.

**Comment by le-ander** [comment]
can you point me to an example where this applies?

**Comment by davidsebfischer** [comment]
Sorry missed the copy above: https://github.com/theislab/sfaira/blob/8803db5642fac48b4b27c443d9f82e7f5eedde0e/sfaira/data/dataloaders/loaders/d10_1016_j_cell_2017_09_004/human_pancreas_2017_smartseq2_enge_001.py#L22.

**Comment by le-ander** [comment]
ah I see so basically the user will never preprocess data themselves if they want a cached object. they would rather do the caching through sfaira using the raw loading code once. correct?

**Comment by le-ander** [comment]
closed by #38
