### ISSUE TITLE
tensorflow-gpu is in extras_require, but is contained in the 2.x tensorflow packages anyways

### ISSUE THREAD

**Issue by Zethson** [theislab/sfaira#71]
Since Tensorflow 2.x tensorflow-gpu is usually already contained in the normal tensorflow package. Source: https://www.tensorflow.org/install/gpu

The Tensorflow maintainers fucked up once so one of the versions (2.2? I don't remember) does not fully adhere to this, but the newest versions should all be fine.

I would suggest to drop tensorflow-gpu, because it won't really be maintained in the future and cause mores issues than benefit.

Is there a special reason for the tensorflow-gpu dependency @davidsebfischer ?

**Comment by davidsebfischer** [comment]
No, this is just legacy because this was used in previously tf 1.* versions. We can depreceate it because we can reasonably ask everybody to use 2.* now!

**Comment by Zethson** [comment]
Then I will take care of this :)

**Comment by Zethson** [comment]
I'll close this under the assumption that #38 will get merged very soon.
