### ISSUE TITLE
UserWarning: DatasetGroupDirectoryOriented was None for d10_1038_s41593_019_0393_4

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#84]
When running `sfaira.data.dataloaders.DatasetSuperGroupSfaira(path=datadir, meta_path=metadir)` I get:
`UserWarning: DatasetGroupDirectoryOriented was None for d10_1038_s41593_019_0393_4`

This is because for some inexplicable reason ```pydoc.locate("sfaira.sfaira.data.dataloaders.loaders.d10_1038_s41593_019_0393_4.FILE_PATH")```
returns `None`, even though `__init__.py` is present for this doi directory like it is for all others.

All other datasets seem fine. Any idea?

**Comment by davidsebfischer** [comment]
At first glance I am also not sure where this might be coming from. The meta data writing unit tests also seems to have ommitted it.

**Comment by davidsebfischer** [comment]
Let's see whether it is still an issue after #85 is merged, might be solved there.

**Comment by le-ander** [comment]
yes, bug no longer occurring on latest dev
