### ISSUE TITLE
Organoid Ontology

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#86]
As discussed previously, here is how we would structure out organoid metadata:

* on top level, we would distinguish between 1. primary tissue samples (all the data that's in sfaira already) and 2. cell-culture samples (organoids would be one subcategory of cell-culture samples)
* any cell-culture samples would have metadata fields for both: 1. source celltype [defined by a celltype ontology] (with cell-line appended to the name [freetext]) and 2. target tissue / target celltype [defined by a anatomical ontology]
* additional fields:
  * protocol [freetext]
  * protocol type [guided/unguided]
  * age [does this need to be different from age in primary tissue?]
  * perturbation [freetext]
  * species [as for primary tissue]?

**Comment by le-ander** [comment]
After discussing with different parties (luke, group meeting, bio organoid people @ MPI). This is where I curerntly stand with the organoid ontology:

Miscelaneous feedback that I think make sense to incorporate:
- don't introduce self.source_celltype (the bio people mentioned that there is no evidence that the source celltype has any meaningful effect on the cellline. Ie. there is no evidence that says that 2 fibroblast-derived cellines are more similar to each other than a fibrobalst derived and a blood derived celline)
- use 2D / 3D culture instead of homgeneous / heterogenous culture as sample_source label (apparently, from a bio perspective, hardly any celline differentiation experiment will be truly homogenous apart form some cancer stuff)

Changed fields:
- [ ] rename self.protocol to self.sc_protocol (I think this as changes to self.assay in a recent PR, @davidsebfischer do you think "assay" is unambiguous with respect to the addition in-vitro differentiation protocl field, that we're introducting below?)

New Fields:
- [ ] self.sample_source [primary_tissue, 2d_culture, 3d_culture, cancer]
- [ ] self.cellline [freetext or RRID]
- [ ] self.target_tissue [UBERON]
- [ ] self.target_celltype [CL]
- [ ] self.differentiation_protocol [freetext]
- [ ] self.differentiation protocol [guided, unguided]
- [ ] self.culture_age [number of days]

@davidsebfischer any more feedback from your side? otherwise I'd go ahead and implement this in a PR.

**Comment by davidsebfischer** [comment]
- let' rename `assay` to `assay_sc` in the future, let's not do it now because there a couple of things chaning in this code. I used assay because CZI is using it.
- let's add `assay_differentiation` etc then, so that it s clear that these are further defining the assay
- let's usetissue and celltype instead of target_tissue and target_celltype because we only have one of these now that we removed source*?
- let's use age for what you want in culture_age?
- constraining cell lines might really add information. we could add both freetext and RRID if sensible?

**Comment by le-ander** [comment]
> constraining cell lines might really add information. we could add both freetext and RRID if sensible?
What's the canonical way to integrate a database like RRID (which does not seem to provide and obo/owl files) into sfaira? @davidsebfischer

**Comment by davidsebfischer** [comment]
Do you have a link for that?

**Comment by le-ander** [comment]
https://scicrunch.org/resources/Cell%20Lines/search?l=&q=%2A

**Comment by davidsebfischer** [comment]
The core representation that you need to do relational reasoning with such ontologies is a `nodes x nodes` directed sparse edge matrix that represents the DAG. You can either directly build this if you have access to the full graph, e.g. from `obo`'s, or you need an interface that can query whether edges exists between any 2 nodes, e.g. based on an API, such as exposed by EBI. I would think that one of the two is possible, this here suggests that this stored somewhere https://web.expasy.org/cellosaurus/CVCL_A1RT.txt. The absolute minimal case would be to require entires for this meta data entry to be follow their nomenclature, but not representing the hierarchies via edges.

**Comment by le-ander** [comment]
Todo:

- [ ] include cellosaurus ontology
- [ ]
